name: Test Documentation

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

env:
  # Install packages into system environment.
  # Follows: https://docs.astral.sh/uv/guides/integration/github/#using-uv-pip
  UV_SYSTEM_PYTHON: 1

jobs:
  detect-code-changes:
    name: Detect Code Changes
    runs-on: ubuntu-latest
    outputs:
      run-tests: ${{ steps.filter.outputs.run-tests }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          list-files: shell
          filters: |
            run-tests:
              - '!docker/**'
              - '!.github/**'
              - '.github/workflows/test_documentation.yml'
  test-documentation:
    name: Test Documentation
    needs: detect-code-changes
    if: needs.detect-code-changes.outputs.run-tests == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set Up uv
        uses: astral-sh/setup-uv@v5
        id: setup-uv
        with:
          version: 0.10.0
          enable-cache: true
          cache-dependency-glob: "**/pyproject.toml"
          python-version: "3.13"
      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Set Up Environment
        run: |
          make install-docs
      - name: Build
        run: |
          cd docs && make docs docs-stable
